#!/usr/bin/env bash

_status_file="${XDG_RUNTIME_DIR}/presentation-mode-on"
_autostart="$HOME/.autostart.sh"

is_on() {
    [[ -e "${_status_file}" ]]
}

switch_on() {
    touch "${_status_file}"
    dunstctl disable &
    systemctl --user --no-block stop user:redshift
    systemctl --user --no-block stop user:spotify
}

switch_off() {
    rm -f "${_status_file}"
    dunstctl enable &
    "$_autostart" redshift spotify
}


case "$1" in
    status)
        if is_on ; then
            printf "on\n"
            printf '#F4BF75'
        else
            printf "off\n"
            # printf '#F4BF75'
        fi
        ;;
    toggle)
        if is_on ; then
            switch_off
        else
            switch_on
        fi
        ;;
    off)
        switch_off
        ;;
    on)
        switch_on
        ;;
esac


