#!/usr/bin/env bash

load="$(cut -d ' ' -f 1 /proc/loadavg)"
cpus="$(nproc --all)"

echo $load
echo $load

awk -v cpus=$cpus -v _load=$load '
    BEGIN {
        if (_load >= cpus) {
            print "#FF0000";
        }
        else if (_load >= cpus / 2) {
            print "#FFFF00";
        }
    }'
