_path=("$HOME/bin"
       "/usr/local/sbin"
       "/usr/local/bin"
       "/usr/sbin"
       "/usr/bin"
       "/sbin"
       "/bin"
       "/usr/bin/core_perl"
       "/usr/games")

PATH=""
for part in ${_path[@]} ; do
    PATH="$PATH:${part}"
done
PATH="${PATH#:}"
export PATH

export EDITOR="vim"
export VISUAL="vim"
export BROWSER="firefox"

export PAGER="less"
export LESS="FRX"

export VIMRC="$HOME/.vimrc"

export WINEPATH="$HOME/games/wine"

export LOGDIR="$HOME/.var/log"
export RUNDIR="$HOME/.var/run"
export LIBDIR="$HOME/.var/lib"
export BINDIR="$HOME/bin"

export LANG=en_US.UTF-8
export LC_TIME=de_DE.UTF-8
export LC_COLLATE=C

export DOTFILES=~/dotfiles


# Start the gpg-agent if not already running
if ! pgrep -x --uid "${USER}" gpg-agent >/dev/null 2>&1; then
    eval $(gpg-agent --daemon --sh)
fi

# because gpg-agent is somehow broken for ssh, use the usual ssh-agent
eval $(ssh-agent -s)

# exec startx breaks some logind fuckery, without exec it works
if [[ -z $DISPLAY ]] ; then
    if (( $XDG_VTNR == 1 )) ; then
        startx
    else
        tmux new-session -A -s tmux-tty-$XDG_VTNR
    fi
fi
