# exec startx breaks some logind fuckery, without exec it works
#tmux start-server &
eval $(ssh-agent -s)

export EDITOR="vim"
export VISUAL="vim"
export PATH="$HOME/bin:$PATH"
export BROWSER="firefox"

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx
