[[ -z "$PS1" ]] && return

_files=(
    'shellopts'
    'functions'
    'variables'
    'aliases'
    'prompt')

for file in "${_files[@]}" ; do
    _path="$HOME"/.zsh/"$file".sh
    if [[ -e "$_path" ]] ; then
        source "$_path"
    fi
done
